name: Daily Supermarket Scraper Run

on:
  #run on the push
  push:
    branches:
      - main
  # schedule:
  #   #run every day at 12:00 UTC
  #   - cron: '0 12 * * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Asegúrate de usar la versión de Python que necesites

    - name: Install Chrome WebDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-driver
        echo "CHROMEWEBDRIVER=/usr/bin/chromium-driver" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium webdriver_manager

    - name: Run script
      run: python main.py --correr-todo
